name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - Seguridad
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2 # Actualiza a v2
      - name: Set up JDK
        uses: actions/setup-java@v2 # Actualiza a v2
        with:
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v2 # Actualiza a v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and Test
        run: mvn -B test
